name: bank_churn_model
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.4.1
  - ipython=7.28.0
  - jupyterlab=3.2.0
  - matplotlib=3.4.3
  - numpy=1.21.2
  - pandas=1.3.3
  - pip=21.3
  - python=3.9.7
  - scikit-learn=1.0
  - seaborn=0.11.2
  - pip:
    - streamlit==1.0.0
    - xgboost==1.4.2
